# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Gutenberg Reader' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Gutenberg Reader
  pod 'SwiftHTTP', '~> 2.0.2'
  pod 'FolioReaderKit', '~> 1.1.0'

  target 'Gutenberg ReaderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Gutenberg ReaderUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
